template: git@git.k-space.ee:codemowers/lab-template
cluster:
  name: codemowers.eu
  server: https://kube.codemowers.eu
  oidc-issuer-url: https://dex.codemowers.eu
sandboxLinks:
- name: shared-longhorn
  icon: https://cncf-branding.netlify.app/img/projects/longhorn/icon/color/longhorn-icon-color.png
  url: https://longhorn.codemowers.eu/#/volume?field=namespace&value={{ sandbox.namespace }}
- name: shared-argocd
  icon: https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png
  url: https://argocd.codemowers.eu/applications/{{ sandbox.namespace }}?resource=&view=network
- name: shared-traefik
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Traefik.logo.png/174px-Traefik.logo.png
  url: https://traefik.codemowers.ee/dashboard/#/http/routers?filter={{ sandbox.namespace }}
- name: dedicated-traefik
  feature: traefik
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Traefik.logo.png/174px-Traefik.logo.png
  url: https://traefik{{ sandbox.hostname_suffix }}/dashboard/
- name: shared-prometheus
  icon: https://cncf-branding.netlify.app/img/projects/prometheus/icon/color/prometheus-icon-color.png
  url: https://prom.codemowers.eu/graph?g0.expr=%7Bnamespace%3D%22{{ sandbox.namespace }}%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
- name: dedicated-prometheus
  feature: prometheus
  icon: https://cncf-branding.netlify.app/img/projects/prometheus/icon/color/prometheus-icon-color.png
  url: https://prom{{ sandbox.hostname_suffix }}/graph?g0.expr=%7Bnamespace%3D%22{{ sandbox.namespace }}%22%2Cpod%3D%22%(pod)%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
- name: shared-logging
  icon: fa-solid fa-clock-rotate-left
  url: https://log.codemowers.eu/?kubernetes.namespace={{ sandbox.namespace }}
podLinks:
- name: logs
  url: https://log.codemowers.eu/?kubernetes.namespace={{ sandbox.namespace }}&kubernetes.pod.name={{ pod }}
  icon: fas fa-clock-rotate-left
- name: monitoring
  icon: fas fa-chart-line
  url: https://prom{{ sandbox.hostname_suffix }}/graph?g0.expr=%7Bnamespace%3D%22%(namespace)s%22%2Cpod%3D%22%(pod)%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
features:
- name: prometheus
  description: "Set up dedicated Prometheus instance for this sandbox"
  default: true
  icon: https://cncf-branding.netlify.app/img/projects/prometheus/stacked/color/prometheus-stacked-color.png
- name: logging
  description: "Enable logging with shared Logmower instance"
  default: true
  link: https://log.codemowers.eu/?namespaces
- name: traefik
  description: "Set up dedicated Traefik instance for this sandbox"
  default: false
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Traefik.logo.png/174px-Traefik.logo.png
- name: harbor_project
  description: "Set up Docker registry push/pull secrets for Skaffold use"
  default: true
  icon: https://cncf-branding.netlify.app/img/projects/harbor/stacked/color/harbor-stacked-color.png
- name: subdomain
  default: false
  description: "Create dedicated subdomain under codemowers.cloud"
- name: dex
  description: "Dedicated Dex instance"
  default: false
  icon: https://cncf-branding.netlify.app/img/projects/dex/stacked/color/dex-stacked-color.png
- name: argocd
  description: "Set up separate ArgoCD instance for this namespace"
  default: false
  icon: https://cncf-branding.netlify.app/img/projects/argo/stacked/color/argo-stacked-color.png
